module.exports = {
	databaseOption: {},
	// baseUrlServer: 'http://localhost:3000/andco_server/uploads/pdf/',
	baseUrl: 'http://localhost:4200/',
	forgotPasswordLink: '/#/forgot-password/',
	welcomeGuest: '/#/welcome-guest/',
	emailVerificationLink: '/#/email-verify/',
	fbUrl: 'https://graph.facebook.com/v2.10/me',
	googleUrl: 'https://www.googleapis.com/oauth2/v3/tokeninfo?id_token=',
	googleClientId: '261246561965-ikogp2hbouqaj7l9deflfr176lqa3p3u.apps.googleusercontent.com',
	outLookUrl: 'https://graph.microsoft.com/v1.0/me/',
	yahooUrl: 'https://social.yahooapis.com/v1/user/',
	jwtSecret: 'asoebi',
	ngrockUrl: 'https://test.andcowith.me:9001/',
};